env: JRUBY_OPTS=--debug
dist: trusty
language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - jruby-9.2.5.0
  - 2.6.3
  - 2.5.6
  - 2.4.6
before_install:
  - sudo apt-get install -y libgl1-mesa-dev
  - gem update --system
  - gem install bundler
script: bundle exec rake build spec
